name: work
description: A project for workroom
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
#语言国际化
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.2
  animations: ^2.0.1
  rxdart: ^0.27.1 #全局消息处理器
  flutter_bloc: ^7.0.1  #业务逻辑和UI组件分离开。BLoC模式下的应用程序，一般会有全局的BLoC，每一个页面也会对应有一个独立的BLoC
  equatable: ^2.0.3 #相等比较
  shared_preferences: ^2.0.6 # flutter 持久化插件
  collection: ^1.15.0
  package_info_plus: ^1.0.3 #包信息
  fl_chart: ^0.36.2 #图形
  path_provider: ^2.0.2 #文件管理
  path: ^1.8.0
  json_annotation: ^4.0.1 #json转models
  url_strategy: ^0.2.0 #处理web#号问题
  flutter_smart_dialog: ^2.1.6
  adaptive_breakpoints: ^0.0.4
  url_launcher: ^6.0.9
  animated_text_kit: ^4.2.1 #艺术文字
  flutter_gallery_assets: ^1.0.2 #图片
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  
flutter:

  uses-material-design: true
#国际化
  generate: true # 添加这一行
  assets:
    - assets/images/
    - assets/studies/
  fonts: # 配置字体，可配置多个，支持ttf和otf,ttc等字体资源
    - family: IndieFlower #字体名
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: BalooBhai2 #字体名
      fonts:
        - asset: assets/fonts/BalooBhai2-Regular.ttf
    - family: Inconsolata #字体名
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
    - family: Neucha #字体名
      fonts:
        - asset: assets/fonts/Neucha-Regular.ttf
    - family: ComicNeue #字体名
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
    - family: TolyIcon
      fonts:
        - asset: assets/iconfont/iconfont.ttf
